name: Update Stock Data
on:
  schedule:
    - cron: '0 18 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas fastparquet pyarrow numpy

      - name: Run Downloader
        run: python downloader.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add market_data.parquet
          git commit -m "Auto-update market data" || echo "No changes to commit"
          git push
